const COMPANY_URL_MAP: Record<string, string> = {
  // AI/ML
  openai: "https://openai.com",
  anthropic: "https://anthropic.com",
  scaleai: "https://scale.com",
  "scale-ai": "https://scale.com",
  databricks: "https://databricks.com",
  huggingface: "https://huggingface.co",
  stabilityai: "https://stability.ai",
  "stability-ai": "https://stability.ai",
  ai21: "https://ai21.com",
  cohere: "https://cohere.com",
  replicate: "https://replicate.com",
  runway: "https://runwayml.com",
  inflection: "https://inflection.ai",
  "character-ai": "https://character.ai",
  "character.ai": "https://character.ai",
  jasper: "https://jasper.ai",
  "copy-ai": "https://copy.ai",
  "copy.ai": "https://copy.ai",
  groq: "https://groq.com",
  "together-ai": "https://together.ai",
  "fireworks-ai": "https://fireworks.ai",
  modal: "https://modal.com",
  weightsandbiases: "https://wandb.ai",
  "Weights-Biases": "https://wandb.ai",
  snorkelai: "https://snorkel.ai",
  soundhound: "https://soundhound.com",

  // Big Tech
  airbnb: "https://airbnb.com",
  stripe: "https://stripe.com",
  figma: "https://figma.com",
  notion: "https://notion.so",
  discord: "https://discord.com",
  reddit: "https://reddit.com",
  cloudflare: "https://cloudflare.com",
  twilio: "https://twilio.com",
  gitlab: "https://gitlab.com",
  grafana: "https://grafana.com",
  elastic: "https://elastic.co",
  datadog: "https://datadog.com",
  snowflake: "https://snowflake.com",
  hashicorp: "https://hashicorp.com",
  confluent: "https://confluent.io",
  mongodb: "https://mongodb.com",
  splunk: "https://splunk.com",
  dynatrace: "https://dynatrace.com",

  // Fintech
  plaid: "https://plaid.com",
  square: "https://squareup.com",
  coinbase: "https://coinbase.com",
  robinhood: "https://robinhood.com",
  revolut: "https://revolut.com",
  wise: "https://wise.com",
  nubank: "https://nubank.com.br",
  chime: "https://chime.com",
  brex: "https://brex.com",
  ramp: "https://ramp.com",
  carta: "https://carta.com",
  deel: "https://deel.com",
  remote: "https://remote.com",
  checkout: "https://checkout.com",
  n26: "https://n26.com",
  monzo: "https://monzo.com",
  anduril: "https://anduril.com",

  // DevTools
  vercel: "https://vercel.com",
  netlify: "https://netlify.com",
  supabase: "https://supabase.com",
  railway: "https://railway.app",
  postman: "https://postman.com",
  snyk: "https://snyk.io",
  linear: "https://linear.app",
  height: "https://height.app",
  shortcut: "https://shortcut.com",
  miro: "https://miro.com",
  loom: "https://loom.com",
  calendly: "https://calendly.com",
  airtable: "https://airtable.com",
  asana: "https://asana.com",
  doordash: "https://doordash.com",
  instacart: "https://instacart.com",
  canva: "https://canva.com",

  // Robotics
  nuro: "https://nuro.ai",
  zoox: "https://zoox.com",
  waymo: "https://waymo.com",
  cruise: "https://getcruise.com",
  "boston-dynamics": "https://bostondynamics.com",
  figure: "https://figure.ai",
  apptronik: "https://apptronik.com",

  // Recruiting platforms
  lever: "https://lever.co",
  greenhouse: "https://greenhouse.io",
  ashby: "https://ashbyhq.com",
  beamery: "https://beamery.com",
  smartrecruiters: "https://smartrecruiters.com",
  eightfold: "https://eightfold.ai",
  phenom: "https://phenom.com",
  clari: "https://clari.com",
  gong: "https://gong.io",
  outreach: "https://outreach.io",
  salesloft: "https://salesloft.com",
  hubspot: "https://hubspot.com",
  salesforce: "https://salesforce.com",

  // Streaming / Media
  netflix: "https://netflix.com",
  spotify: "https://spotify.com",
  disney: "https://disney.com",
  hulu: "https://hulu.com",
  twitch: "https://twitch.tv",
  vimeo: "https://vimeo.com",
  quora: "https://quora.com",
  medium: "https://medium.com",
  substack: "https://substack.com",

  // Otta companies
  deliveroo: "https://deliveroo.com",

  // Other
  palantir: "https://palantir.com",
  flexport: "https://flexport.com",
  segment: "https://segment.com",
  amplitude: "https://amplitude.com",
  mixpanel: "https://mixpanel.com",
  fullstory: "https://fullstory.com",
  hotjar: "https://hotjar.com",
  rippling: "https://rippling.com",
};

export function getCompanyUrl(tokenOrSlug: string): string {
  const normalized = tokenOrSlug.toLowerCase();
  return COMPANY_URL_MAP[normalized] ?? `https://${normalized}.com`;
}
